name: New gems
description: Add a message in Pull Request with basic information when new gems are added
author: aki77
inputs:
  token:
    description: Github token
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
