name: New gems
description: Add a message in Pull Request with basic information when new gems are added
author: aki77
branding:
  icon: check-circle
  color: red
inputs:
  token:
    description: Github token
    default: "${{ github.token }}"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
